use quick_xml::events::BytesStart;
use std::io::Read;

use crate::excel::XmlReader;

use crate::common_types::HexColor;
use crate::helper::extract_val_attribute;

use super::color_transforms::XlsxColorTransform;

/// https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.drawing.presetcolor?view=openxml-3.0.1
/// Example
/// ```
/// <a:prstClr val="black" />
/// ```
// tag: prstClr
#[derive(Debug, Clone, PartialEq)]
pub struct XlsxPresetColor {
    // attributes:
    /// Allowed value: https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.drawing.presetcolorvalues?view=openxml-3.0.1
    pub val: Option<String>,

    // children
    pub color_transforms: Option<Vec<XlsxColorTransform>>,
}

impl XlsxPresetColor {
    pub(crate) fn load(reader: &mut XmlReader<impl Read>, e: &BytesStart) -> anyhow::Result<Self> {
        let val = extract_val_attribute(e)?;
        let mut color = Self {
            val,
            color_transforms: None,
        };

        color.color_transforms = Some(XlsxColorTransform::load_list(reader, b"prstClr")?);

        Ok(color)
    }
}

impl XlsxPresetColor {
    #[allow(dead_code)]
    pub(crate) fn to_hex(&self) -> Option<HexColor> {
        if self.val.is_none() {
            return None;
        }
        let _ = match self.val.clone().unwrap().as_ref() {
            "aliceBlue" => (),
            "antiqueWhite" => (),
            "aqua" => (),
            "aquamarine" => (),
            "azure" => (),
            "beige" => (),
            "bisque" => (),
            "black" => (),
            "blanchedAlmond" => (),
            "blue" => (),
            "blueViolet" => (),
            "brown" => (),
            "burlyWood" => (),
            "cadetBlue" => (),
            "chartreuse" => (),
            "chocolate" => (),
            "coral" => (),
            "cornflowerBlue" => (),
            "cornsilk" => (),
            "crimson" => (),
            "cyan" => (),
            "dkBlue" => (),
            "darkBlue" => (),
            "dkCyan" => (),
            "darkCyan" => (),
            "dkGoldenrod" => (),
            "darkGoldenrod" => (),
            "dkGray" => (),
            "darkGray" => (),
            "dkGreen" => (),
            "darkGreen" => (),
            "dkGrey" => (),
            "darkGrey" => (),
            "dkKhaki" => (),
            "darkKhaki" => (),
            "dkMagenta" => (),
            "darkMagenta" => (),
            "dkOliveGreen" => (),
            "darkOliveGreen" => (),
            "dkOrange" => (),
            "darkOrange" => (),
            "dkOrchid" => (),
            "darkOrchid" => (),
            "darkRed" => (),
            "dkSalmon" => (),
            "darkSalmon" => (),
            "dkSeaGreen" => (),
            "darkSeaGreen" => (),
            "dkSlateBlue" => (),
            "darkSlateBlue" => (),
            "dkSlateGray" => (),
            "darkSlateGray" => (),
            "dkSlateGrey" => (),
            "darkSlateGrey" => (),
            "dkTurquoise" => (),
            "darkTurquoise" => (),
            "dkViolet" => (),
            "darkViolet" => (),
            "deepPink" => (),
            "deepSkyBlue" => (),
            "dimGray" => (),
            "dimGrey" => (),
            "dodgerBlue" => (),
            "firebrick" => (),
            "floralWhite" => (),
            "forestGreen" => (),
            "fuchsia" => (),
            "gainsboro" => (),
            "ghostWhite" => (),
            "gold" => (),
            "goldenrod" => (),
            "gray" => (),
            "green" => (),
            "greenYellow" => (),
            "grey" => (),
            "honeydew" => (),
            "hotPink" => (),
            "indianRed" => (),
            "indigo" => (),
            "ivory" => (),
            "khaki" => (),
            "lavender" => (),
            "lavenderBlush" => (),
            "lawnGreen" => (),
            "lemonChiffon" => (),
            "ltBlue" => (),
            "lightBlue" => (),
            "ltCoral" => (),
            "lightCoral" => (),
            "ltCyan" => (),
            "lightCyan" => (),
            "ltGoldenrodYellow" => (),
            "lightGoldenrodYellow" => (),
            "ltGray" => (),
            "lightGray" => (),
            "ltGreen" => (),
            "lightGreen" => (),
            "ltGrey" => (),
            "lightGrey" => (),
            "ltPink" => (),
            "lightPink" => (),
            "ltSalmon" => (),
            "lightSalmon" => (),
            "ltSeaGreen" => (),
            "lightSeaGreen" => (),
            "ltSkyBlue" => (),
            "lightSkyBlue" => (),
            "ltSlateGray" => (),
            "lightSlateGray" => (),
            "ltSlateGrey" => (),
            "lightSlateGrey" => (),
            "ltSteelBlue" => (),
            "lightSteelBlue" => (),
            "ltYellow" => (),
            "lightYellow" => (),
            "lime" => (),
            "limeGreen" => (),
            "linen" => (),
            "magenta" => (),
            "maroon" => (),
            "medAquamarine" => (),
            "mediumAquamarine" => (),
            "medBlue" => (),
            "mediumBlue" => (),
            "medOrchid" => (),
            "mediumOrchid" => (),
            "medPurple" => (),
            "mediumPurple" => (),
            "medSeaGreen" => (),
            "mediumSeaGreen" => (),
            "medSlateBlue" => (),
            "mediumSlateBlue" => (),
            "medSpringGreen" => (),
            "mediumSpringGreen" => (),
            "medTurquoise" => (),
            "mediumTurquoise" => (),
            "medVioletRed" => (),
            "mediumVioletRed" => (),
            "midnightBlue" => (),
            "mintCream" => (),
            "mistyRose" => (),
            "moccasin" => (),
            "navajoWhite" => (),
            "navy" => (),
            "oldLace" => (),
            "olive" => (),
            "oliveDrab" => (),
            "orange" => (),
            "orangeRed" => (),
            "orchid" => (),
            "paleGoldenrod" => (),
            "paleGreen" => (),
            "paleTurquoise" => (),
            "paleVioletRed" => (),
            "papayaWhip" => (),
            "peachPuff" => (),
            "peru" => (),
            "pink" => (),
            "plum" => (),
            "powderBlue" => (),
            "purple" => (),
            "red" => (),
            "rosyBrown" => (),
            "royalBlue" => (),
            "saddleBrown" => (),
            "salmon" => (),
            "sandyBrown" => (),
            "seaGreen" => (),
            "seaShell" => (),
            "sienna" => (),
            "silver" => (),
            "skyBlue" => (),
            "slateBlue" => (),
            "slateGray" => (),
            "slateGrey" => (),
            "snow" => (),
            "springGreen" => (),
            "steelBlue" => (),
            "tan" => (),
            "teal" => (),
            "thistle" => (),
            "tomato" => (),
            "turquoise" => (),
            "violet" => (),
            "wheat" => (),
            "white" => (),
            "whiteSmoke" => (),
            "yellow" => (),
            "yellowGreen" => (),
            _ => return None,
        };
        return None;
    }
}
